name: Build (Windows amd64)
on:
  push:
    branches: [ master ]
jobs:
  build-windows-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone vcpkg
      run: git clone --depth 1 https://github.com/microsoft/vcpkg
      shell: pwsh
    - name: Bootstrap vcpkg
      run: .\vcpkg\bootstrap-vcpkg.bat
      shell: pwsh
    - name: Integrate vcpkg
      run: .\vcpkg\vcpkg integrate install
      shell: pwsh
    - name: mkdir
      run: mkdir build
      shell: pwsh
    - name: cmake build
      run: cmake -Bbuild --preset release-vcpkg -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: pwsh
    - name: cmake make
      run: cmake --build build/ --preset release-vcpkg --config Release
      shell: pwsh
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/src/Release