name: Build (Ubuntu AMD64)
on:
  push:
    branches: [ next ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev libzip-dev
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H. -DBUILD_SHARED_LIBS=0
    - name: cmake make
      run: cmake --build build/ --target all
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: binary
        path: build/src/cork