name: Build (Debian aarch64)
on:
  push:
    branches: [ next ]
jobs:
  build-debian-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2
      name: Builds Cork
      id: build
      with:
        arch: aarch64
        distro: bullseye

        boost: sudo apt-get update && sudo apt-get install -yq libboost-all-dev libzip-dev
        dir: mkdir build
        build: cmake -Bbuild -H. -DBUILD_SHARED_LIBS=0
        make: cmake --build build/ --target all
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: binary
        path: build/src/cork