name: Package (Fedora amd64)
on:
  push:
    branches: [ next ]
jobs:
  package-fedora-amd64:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo dnf -y -q upgrade --refresh
    - name: build tools
      run: sudo dnf install -y git cmake make automake gcc gcc-c++ rpm-build
    - name: libraries
      run: sudo dnf install -y boost-devel libzip-devel zlib-devel bzip2-devel xz-devel openssl-devel curl-devel
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCPACK_GENERATOR=RPM -DCPR_USE_SYSTEM_CURL=ON
    - name: cmake make
      run: cmake --build build/ --target all
    - name: cpack
      run: cd build && cpack
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: build/cork.x86_64.rpm