name: Package (Ubuntu amd64)
on:
  push:
    branches: [ master ]
jobs:
  package-ubuntu-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: libraries
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev libzip-dev curl libcurl4-openssl-dev liblua5.4-dev
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild --preset release -DCPACK_GENERATOR=DEB -DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON
    - name: cmake make
      run: cmake --build build/ --preset release --target all
    - name: cpack
      run: cd build && cpack
    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: build/cork.x86_64.deb